# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

# Much of the information is available via:
#  pnpm info node-red
# The sha256 is currently not available from these sources. 
context:
  name: node-red
  version: "4.0.9"
  sha: d8548204752c8ed7c1c5648e6fe2843342797ff5f0214647bdd1078366811cba

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://registry.npmjs.org/${{ name }}/-/${{ name }}-${{ version }}.tgz
    sha256: ${{ sha }} 
    file_name: ${{ name }}-${{ version }}.tgz
  - path: node-red.cmd
    target_directory: bin
 
build:
  number: 0
  script: |
    tar xvzf ${{ name }}-${{ version }}.tgz --strip-components=1 --directory $PREFIX
    cd $PREFIX
    pnpm install
    pnpm add semver
    pnpm-licenses generate-disclaimer --prod --output-file=$SRC_DIR/third-party-licenses.txt

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs
    - pnpm

tests:
  - script:
      # - find . -maxdepth 3
      - pnpm start --help
      - test -f bin/node-red.cmd

about:
  homepage: https://nodered.org
  summary: 'Low-code programming for event-driven applications'
  description: |
     Node-RED's goal is to enable anyone to build applications that collect,
     transform and visualize their data; 
     building flows that can automate their world. 
     Its low-code nature makes it accessible to users of any background, 
     whether for home automation,
     industrial control systems or anything in between.
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - https://github.com/node-red/node-red/blob/master/LICENSE
    - third-party-licenses.txt
  documentation: https://nodered.org/docs/
  repository: https://github.com/node-red/node-red

extra:
  recipe-maintainers:
    - phreed
