schema_version: 1

# Much of the information is available via:
context:
  group: mumble-voip
  name: mumble
  version: "1.5.735"
  sha: 539680318419ca6c236d129dc5b6a96878bd048957cfcfb3882d313dd16660fa
  git_rel: github.com/${{ group }}/${{ name }}

package:
  version: ${{ version }}
  name: ${{ name|lower }}
  
source:
  url: https://${{ git_rel }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha }}
  target_directory: src/mumble
  patches:
    - patches/0000-null.patch

# https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/README.md
build:
  number: 0
  script:
    env:
      JOB_CNT: ${{ nprocs }}   
    interpreter: nu
    content: |
      cd src/mumble
      cmake -B build -DCMAKE_BUILD_TYPE=Release -Dspeechd=OFF -Dstatic=ON
      cd build
      cmake --build . -j $env.JOB_CNT
      cmake --install .

requirements:
  build:
    - nushell
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - python
    - cmake
    - ninja
    - if: unix
      then: make
    - pkg-config
    - libopenssl-static
    - libprotobuf-static
    - protobuf
  host:
    - ${{ stdlib('c') }}
    - qt6-main
    - qt6-wayland 
    - xorg-libxi
    - libboost-devel
    - libgl-devel
    - alsa-lib
    - libcap
    - libogg
    - libsndfile
    - libopus
    # - libspeechd
    - avahi
    - libxcb
    - zeroconf
    - poco

tests:
  - script: 
      - "mumble --help 2>&1"

about:
  homepage: https://www.mumble.info/
  summary: 'Mumble is a free, open source, low latency, high quality voice chat application.'
  description: |
     Mumble was the first VoIP application to establish true low latency voice communication over a decade ago.
     But low latency and gaming are not the only use cases it shines in.
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - https://www.mumble.info/LICENSE
    - library_licenses
  documentation: https://www.mumble.info/documentation/
  repository: https://github.com/mumble-voip/mumble

extra:
  recipe-maintainers:
    - phreed
