{% set name = "testresources" %}
{% set version = "2.0.1" %}
{% set python_min = "3.7" %}
{% set python_max = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/testresources-{{ version }}.tar.gz
  sha256: ee9d1982154a1e212d4e4bac6b610800bfb558e4fb853572a827bc14a96e4417

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pbr >=1.3
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - testresources
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://launchpad.net/testresources
  summary: Testresources, a pyunit extension for managing expensive test resources
  license: JSON
  license_file: COPYING

extra:
  recipe-maintainers:
    - phreed
