#!/usr/bin/env bash

# NOTE: This script has been adapted from content generated by github.com/conda-forge/conda-smithy

source .scripts/logging_utils.sh

( startgroup "Configure Docker" ) 2> /dev/null

# set -eo pipefail
SET_OPTIONS=$(set +o)

REPO_ROOT=$(cd "$(dirname "$0")/.."; pwd;)
ARTIFACTS="$REPO_ROOT/build_artifacts"
THISDIR="$( cd "$( dirname "$0" )" >/dev/null && pwd )"
PROVIDER_DIR="$(basename "$THISDIR")"
AZURE="${AZURE:-False}"

docker info

# In order for the conda-build process in the container to write to the mounted
# volumes, we need to run with the same id as the host machine, which is
# normally the owner of the mounted volumes, or at least has write permission
HOST_USER_ID=$(id -u)
# Check if docker-machine is being used (normally on OSX) and get the uid from
# the VM
if hash docker-machine 2> /dev/null && docker-machine active > /dev/null; then
    HOST_USER_ID=$(docker-machine ssh $(docker-machine active) id -u)
fi

if [ -z "${DOCKER_IMAGE}" ]; then
    SHYAML_INSTALLED="$(shyaml -h || echo NO)"
    if [ "${SHYAML_INSTALLED}" == "NO" ]; then
        echo "WARNING: DOCKER_IMAGE variable not set and shyaml not installed. Trying to parse with coreutils"
        DOCKER_IMAGE=$(cat .ci_support/${CONFIG}.yaml | grep '^docker_image:$' -A 1 | tail -n 1 | cut -b 3-)
        if [ "${DOCKER_IMAGE}" = "" ]; then
            echo "No docker_image entry found in ${CONFIG}. Falling back to quay.io/condaforge/linux-anvil-comp7"
            DOCKER_IMAGE="quay.io/condaforge/linux-anvil-comp7"
        fi
    else
        DOCKER_IMAGE="$(cat "${REPO_ROOT}/.ci_support/${CONFIG}.yaml" | shyaml get-value docker_image.0 quay.io/condaforge/linux-anvil-comp7 )"
    fi
fi

mkdir -p "$ARTIFACTS"
DONE_CANARY="$ARTIFACTS/conda-forge-build-done"
rm -f "$DONE_CANARY"

DOCKER_RUN_ARGS="${CONDA_FORGE_DOCKER_RUN_ARGS}"

if [ "${AZURE}" == "True" ]; then
    DOCKER_RUN_ARGS=""
fi
( endgroup "Configure Docker" ) 2> /dev/null

( startgroup "Start Docker" ) 2> /dev/null

docker pull "${DOCKER_IMAGE}"
CONTAINER_ID=$(docker run -d ${DOCKER_RUN_ARGS} \
           -v "${REPO_ROOT}:/home/conda/staged-recipes" \
           -e HOST_USER_ID=${HOST_USER_ID} \
           -e AZURE=${AZURE} \
           -e PROVIDER_DIR=${PROVIDER_DIR} \
           -e CONFIG \
           -e CI \
           -e CPU_COUNT \
           -e DEFAULT_LINUX_VERSION \
           "${DOCKER_IMAGE}")
CONTAINER_NAME=$(docker inspect --format '{{.Name}}' $CONTAINER_ID | sed 's/^\/\+//')
echo "Container: Name = ${CONTAINER_NAME}, ID = ${CONTAINER_ID}"

( endgroup "Start Docker" ) 2> /dev/null
# docker inspect $CONTAINER_ID

set +e +o pipefail
docker exec -it ${CONTAINER_ID} /bin/bash \
        "/home/conda/staged-recipes/${PROVIDER_DIR}/examine_container.sh" \
        | tee output.log
        # "/home/conda/staged-recipes/${PROVIDER_DIR}/build_steps.sh" \
BUILD_STEPS_STATUS=${PIPESTATUS[0]}
if [ $BUILD_STEPS_STATUS -eq 0 ]; then
  ( startgroup "Stop Docker" ) 2> /dev/null
  docker stop ${CONTAINER_ID}
  docker rm ${CONTAINER_ID}
  ( endgroup "Stop Docker" ) 2> /dev/null
else
  echo "Shell Build Steps Status: $BUILD_STEPS_STATUS"
  docker exec -it ${CONTAINER_ID} bash 
#   exit $BUILD_STEPS_STATUS
fi
eval "$SET_OPTIONS"

# verify that the end of the script was reached
test -f "$DONE_CANARY"

# This closes the last group opened in `build_steps.sh`
( endgroup "Final checks" ) 2> /dev/null
